apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m0s
  url: https://charts.jetstack.io

---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    crds:
      enabled: true
    config:
      enableGatewayAPI: true
