apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori
  namespace: shiori
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
